_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
architecture:
    value: KCL_Explainability
batchSize:
    value: 160
classificationIter_perEp:
    value:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
dataset_id:
    value: KCL
discrimIter_perEp:
    value:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
genIter_perEp:
    value:
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
learning_rate:
    value:
        - 0.0001
        - 0.0001
loassParams:
    value:
        learningRate_dis: 0.0001
        learningRate_gen: 0.0001
        type: wgan
        weights:
            classificationWeight: 1
            descrimFakeWeight: 1
            descrimTrueWeight: 1
            discriminatorWeight: 1
            generatorWeight: 1
            gradWeight: 1
            modificationWeight: 1
lossType:
    value: wgan
modPenalties:
    value:
        method:
            - l1
            - l1_dt
        weights:
            - 0.001
            - 0.001
optimType:
    value: adam
randSeed:
    value: 7777
